# Generated by Django 3.0.5 on 2022-05-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hi',
        ),
    ]
