# Generated by Django 4.0.4 on 2022-05-04 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_bookedseat_id_alter_movie_id_alter_seat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.PositiveSmallIntegerField(unique=True)),
                ('row_no', models.PositiveSmallIntegerField()),
                ('seat_name', models.CharField(max_length=3, unique=True)),
                ('booked_by', models.CharField(blank=True, max_length=200)),
                ('ip', models.CharField(blank=True, max_length=39, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Seats',
            },
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.seats'),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
