# Generated by Django 4.0.4 on 2022-05-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_moviebooked_booked_seats_remove_payment_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('', 'Select'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=8),
        ),
        migrations.AlterField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.show'),
        ),
    ]
